### ISSUE TITLE
Funktionsliste / Anleitung

### ISSUE THREAD

**Issue by riotweb** [dajoho/sleightofhand#3]
Hallo Dave,
der Link http://bit.ly/sleightofhand-site ist leider down. Kannst Du uns bitte die Funktionsübersicht in Github zur Verfügung stellen ?
Thx Markus

**Comment by dajoho** [comment]
Hi Markus,
die Seite ist momentan nicht erreichbar aber die Funktionsübersicht findest du hier: https://web.archive.org/web/20120403010125/http://rex.daveholloway.co.uk/projects/sleightofhand.html

**Comment by dajoho** [comment]
und der @pixelkrieg hatte mal eine Übersicht der Parameter zusammengefasst:

![af98c76c25](https://f.cloud.github.com/assets/952436/2027741/a6279fa2-88be-11e3-83fa-48761d5ecddf.png)
